# Site settings
baseurl = "https://tezos.swiss/"
languageCode = "en-us"
title = "Tezos Foundation"
theme = "hugo-artists-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Tezos Foundation"
	description = "A new digital commonwealth"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "contact@tezos.ch"


	# Header an navigation
	#
	# To change the header background the 'hero-bg-jpg' at 'static/img'.
	# Do the same with the logo ('logo.svg').
	# But keep the original filename!
	[params.header]
		title = "Tezos Foundation"
		shortBio = "A new digital commonwealth"


	# About section
	#
	# Replace the 'avatar.jpg' under 'static/img' with your own image.
	[params.about]
		title = "About Tezos"
		bio = "Tezos is a new decentralized blockchain that governs itself by establishing a true digital commonwealth. It facilitates formal verification, a technique which mathematically proves the correctness of the code governing transactions and boosts the security of the most sensitive or financially weighted smart contracts.
		<break> Tezos has been in development for three years and is being led by Kathleen Breitman, Arthur Breitman, and a development team located in Paris. The advisors to the project are Zooko Wilcox, the founder of ZCash, Emin Gün Sirer, Associate Professor of Computer Science at Cornell University, and Andrew Miller, Assistant Professor of Computer Engineering and Computer Science at the University of Illinois, Urbana-Champaign. There is a working testnet (access is available upon request), and the code is available for review on GitHub.
		<break>White paper
		<break>Position paper
		<break>[Reddit](https://reddit.com/r/tezos)"


	# Contact secion
	[params.contact]
		title = "Contact"

		# The following social network icons are available:
		# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
		# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
		[[params.contact.social]]
			icon = "twitter"
			link = "//twitter.com/devtipsshow"

		[[params.contact.social]]
			icon = "dribbble"
			link = "//dribbble.com/travisneilson"

		[[params.contact.social]]
			icon = "behance"
			link = "//www.behance.net/travisneilson"

		[[params.contact.social]]
			icon = "youtube"
			link = "//www.youtube.com/DevTipsForDesigners"

		[[params.contact.social]]
			icon = "linkedin"
			link = "//www.linkedin.com/in/travisneilson"


	[params.form]
		title = "Contact Us"
		# Form fields
		name = "Your Name"
		email = "Your Email"
		message = "Have a question?"
		buttonText = "Send"


	[params.footer]
		copyright = "Published under the Unlicense License."
