baseurl = "https://www.tezosfoundation.swiss"
languageCode = "fr-fr"
title = "Tezos Foundation"
[params]
  description = "Tezos Foundation"
  mainIcon = "/img/hugo.png"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/tezosfoundation"
[[params.social]]
    title = "github"
    url = "https://github.com/tezos"
[[params.social]]
    title = "linkedin"
    url = ""
